### ISSUE TITLE
Automatic installation of LamBO

### ISSUE THREAD

**Issue by SimonBartels** [MachineLearningLifeScience/poli#104]
The automatic installation of LamBO appears broken. When downloading the dependencies LamBO itself is not installed. I am not sure if the problem is easy to fix. Just adding `"git+https://github.com/samuelstanton/lambo.git@431b052ad0e54a1ba4519272725310127c6377f1"` to the `environment.yml` fails to load the hydra configs.

**Comment by miguelgondu** [comment]
Hi Simon!

Do you have access to the docs? Since we need access to the hydra configs, we currently ask the user to manually clone and `pip install -e .` lambo in the `poli__lambo` environment.

![Screenshot 2023-12-27 at 11 05 47](https://github.com/MachineLearningLifeScience/poli/assets/8268159/e26852d8-167a-4bb6-a977-b4928728a34d)

That being said, I agree: we should try to install `lambo` automatically. I'll work on that for a bit. Since we already have utils for downloading files from GitHub, maybe we could download what we need post-hoc and place it in the `~/poli_objectives` folder.
